### ISSUE TITLE
FTBLib/Utilities

### ISSUE THREAD

**Issue by JorVaCoding** [ModdersCorner/404-Mod-List#11]

**Comment by Lanse505** [comment]
I vote yes!
Since we don't have Chunkloaders or Protection.

**Comment by JorVaCoding** [comment]
Yes to chunkloading. Protection: maybe, It's a trust server, admins have the ability to check if people steal... We have some methods of protection (enderchests, going far away)... When I borrow stuff, I also make sure to leaves signs and return stuff when I can.

**Comment by JorVaCoding** [comment]
https://github.com/ModdersCorner/404-Mod-List/issues/24#issuecomment-234442005

**Comment by yrsegal** [comment]
Doesn't do protection, jorva.

**Comment by JorVaCoding** [comment]
Look at my comment on that issue

**Comment by yrsegal** [comment]
¯\\\_(ツ)_/¯ that's half the reason lanse wants it though

**Comment by JorVaCoding** [comment]
We've partially discussed it in server chat. It's not all the helpful. We don't really need protection.
And if people want protection, build an RFTools force field around their base and don't have a porter. Why put a porter in you base if you don't want people at it and looking around and potentially borrowing?

**Comment by SkySom** [comment]
Shouldn't need protections. I've been working on Lot's of Logging, so soon that'll tattle on your ass. But for the most part, if people can't act like adults and not take what's not theirs, then they can be kicked.

**Comment by JorVaCoding** [comment]
Don't need the extra mods if they aren't going to be used. Chunk loading is nice, but at the same time not fair. Just click and it's loaded, no progression at all.
