### ISSUE TITLE
RFTools Dimensions

### ISSUE THREAD

**Issue by JorVaCoding** [ModdersCorner/404-Mod-List#12]

**Comment by Lanse505** [comment]
I vote a big fat Panda Poop No!
Simply cause if people are concerned about impact on peoples gameplay this mod can get seriously intensive on the server if people just "willeynilley" go and create new dimensions.

**Comment by SkySom** [comment]
My thoughts on if it was to be included, was to keep dimension count low by just creating a few dimension (Mining, void, etc) and just trying to convince people not to create a bunch more.

**Comment by srs-bsns** [comment]
How about use the mod to create a few utility dimensions, like mining, etc.., with public transporters, then use MineTweaker to remove the blocks needed to create more dimensions. This way players can make transporters in their bases to go to those dimensions, but can't create their own dimensions, which probably, as @Lanse505 said, would get out of hand.

**Comment by JorVaCoding** [comment]
@Lanse505 , I'm pretty sure CodedOne and I talked to you about this. All we wanted was a mining world, we were willing to make it legit, but after that, not have any dimensions being built (lag reasons)... My reasoning for still voting yes is because it 
- Is balanced, a player has to find dungeon loot to get dimlits...
- Required power to keep running, so without chunkloading mods (we currently don't have any) , it's not possible to be used, prevents people from running dimensions while not online
- We don't need many uses out of it, 2-3 worlds max. Mining, Void, and maybe one just for exploring (we have overworld so not really needed)...

**Comment by yrsegal** [comment]
It's not balanced, dungeon loot isn't the only way to get dimlets, and there's far too much resource that can be gained for extremely cheap. I vote nay.

**Comment by Eladkay** [comment]
I vote yes. The amount of power required to get a decent unbalanced dimension is far more than anything basic can make in this modpack.
Dimlets also drop from Endermen and we all know how tough Endermen are in this modpack.

**Comment by yrsegal** [comment]
But RF tools provides the means to create such power.

**Comment by warlordjones** [comment]
Endermen aren't really that tough, you just need a half decent sword and some strafing

**Comment by Eladkay** [comment]
RFTools is on the server, nothing will change that

**Comment by yrsegal** [comment]
But we can mitigate the effects of that. Having RFTools Dimensions would just throw balance right out the window.

**Comment by JorVaCoding** [comment]
@yrsegal The RFTools power, 1) takes extremely long time to set up and get timings, 2) Is not very compact, (or cheap)... I think the RFTools power is bad... It creates lots of power, but too much effort goes into it... If you want unfair power, go look at Deep Resonance... And for the Dims being unfair... I don't think it's planned for people to create dimensions freely... We talked about only having 2 (void and mining)...

**Comment by yrsegal** [comment]
so long as it's not planned for survival use, that's fine.

**Comment by JorVaCoding** [comment]
^, We were thinking of making the two dimensions legitly, and then putting them somewhere where admins only can get to it, and giving them creative power... We shouldn't rely on someone's power for the whole server, but it isn't fair just to spawn in the dimensions.

**Comment by SkySom** [comment]
Again I have no clue how you plan to do it legitimately when the world is mostly generated (And thus won't include most of the stuff you need. But yeah RFTools Dims is alright if we leave it to a few agreed upon dimensions (Like JorVa said: Mining (Basically some ore distribution as overworld, but no worry about killing people's bases, void, etc)
