### ISSUE TITLE
Lootable Bodies

### ISSUE THREAD

**Issue by JorVaCoding** [ModdersCorner/404-Mod-List#13]
# RemoveGravesOrRiot

**Comment by warlordjones** [comment]
Personally I think the updated version of Graves works pretty well...

**Comment by JorVaCoding** [comment]
@warlordjones It stills has it bugs though, take for example, our crashes with 2 graves... It's way more stable now but it still isnt the best mod.

**Comment by Lanse505** [comment]
I would like to say I perfer Graves but atm I'm willing to Try Lootable Bodies if it gives us a better experience. However if it's buggier than Graves i suggest we move back.

**Comment by SkySom** [comment]
We used Lootable bodies on another server I was on. And had zero issues with it. Worked quite well.

**Comment by Lanse505** [comment]
In that case i suggest we move over.

**Comment by warlordjones** [comment]
No wearing slime boots anywhere near the end for me, in that case.
