### ISSUE TITLE
Morph-o-tool

### ISSUE THREAD

**Issue by JorVaCoding** [ModdersCorner/404-Mod-List#15]
http://minecraft.curseforge.com/projects/morph-o-tool

Because ic2 wrench is broken

**Comment by Lanse505** [comment]
I vote yes, however @SkySom should still check if the IC2 issue hasn't been fixed in a newer update.

**Comment by SkySom** [comment]
IC2 issue?

**Comment by Lanse505** [comment]
From Jorvas message above
"Because ic2 wrench is broken"

**Comment by JorVaCoding** [comment]
Wrenches don't pick up a machine with shift click (as you've seen with the console spam when I tried too)... The times I had to move my machines (mass fab), I had to get @warlordjones to break it in creative and give it to me... Since breaking with a pickaxe gives a machine casing

**Comment by yrsegal** [comment]
Yes, cleaning up inv space is always a good plan

**Comment by JorVaCoding** [comment]
BUT: I vote no for this mod... It's ic2's issue with not working, not the wrench. I tried two other wrench mods and it didn't work. AND I think we have a universal wrench in the pack already, (From McJty IIRC)

**Comment by yrsegal** [comment]
Morph-o-tool has functionality the universal wrench doesn't by definition.

**Comment by JorVaCoding** [comment]
According to ic2's issue tracker, ic2 version 2.6.12 does work correctly (forge version 2011)

http://bt.industrial-craft.net/view.php?id=1928

**Comment by warlordjones** [comment]
I like it, personally.

**Comment by Eladkay** [comment]
I like it but I don't think it's necessary.

**Comment by SkySom** [comment]
So yeah... This was already on the server.......... Dammit @JorVaCoding
