### ISSUE TITLE
Bullseye

### ISSUE THREAD

**Issue by JorVaCoding** [ModdersCorner/404-Mod-List#16]
http://minecraft.curseforge.com/projects/bullseye

**Comment by TheCodedOne** [comment]
Why?

**Comment by Lanse505** [comment]
Why not?, It's a good mod that adds intressting Non-TiC Arrow Content?

**Comment by TheCodedOne** [comment]
I thought it was a testing server.

**Comment by TheCodedOne** [comment]
Adding mods that dont actually need to be adding will make it harder for those people with bad computers to run the pack.

**Comment by Lanse505** [comment]
How is this not a testable mod?
Just cause it's released?

**Comment by Lanse505** [comment]
Forstride literally released the mod this Tuesday:

Forstride - Last Tuesday at 10:31 PM
Released the first version of my new little mod, Bullseye!  http://minecraft.curseforge.com/projects/bullseye
It adds a handful of new arrow types, including bomb arrows, fire arrows, dye arrows, and more!

**Comment by SkySom** [comment]
Commenting a bit late, but I do wish to put my 2 cent here. I do believe we should be light in what we are adding, and not just add everything. However, I don't see why @TheCodedOne decided this was the mod that would break the camel's back here. Rather than one of the other heavier mods such as RF Dimensions.

**Comment by TheCodedOne** [comment]
@SkySom this was the first mod i saw out of many, but after lanse decided, i just thought, hey whats the point.

**Comment by Lanse505** [comment]
Decided what? 
I opened up the discussion on the subject and decided to debunk the claim that this is a "non-testable mod". You have every right to argue against me on this question hence why we have an open discussion policy here on github.

**Comment by Lanse505** [comment]
My Vote stands as Yes.
It's a small lightweight mod that won't impact performance.

**Comment by yrsegal** [comment]
voting yes!

**Comment by warlordjones** [comment]
I don't mind either way. Also...every mod is testable...

**Comment by srs-bsns** [comment]
Being that @Glitchfiend is also on Discord, maybe they would like to join us and have their mods tested on the server. Bullseye is testable against any other mod that adds bows and/or arrows or custom mobs.
