### ISSUE TITLE
MC 1.10

### ISSUE THREAD

**Issue by SkySom** [ModdersCorner/404-Mod-List#2]
It's coming. Just need to make sure everything works and runs on 1.10

**Comment by AKTheKnight** [comment]
(Bagginses has a separate 1.10 version listed on curse :) )

**Comment by JorVaCoding** [comment]
I say we update on the next update. If most (if not all) mods are compat, We should get it as soon as possible so we can test other things too.

**Comment by SkySom** [comment]
Server now running 1.10.2
