### ISSUE TITLE
Mismatch Grass Color

### ISSUE THREAD

**Issue by Yulife** [ModdersCorner/404-Mod-List#21]
Seems like Building Bricks doesn't take Quark's modified (greener) grass color, thus its grass bricks are more muted and mismatched.

**Comment by Lanse505** [comment]
There was a way to fix this i remember Heav3n telling me.
But it didn't get implemented since it was just when i handed it over to @SkySom

**Comment by hea3ven** [comment]
In quark's config, greener grass is pointing to the wrong block ids. You just need to replace "buildingbrickscompatvanilla" for "buildingbricks".
