### ISSUE TITLE
Author list in WAILA

### ISSUE THREAD

**Issue by Yulife** [ModdersCorner/404-Mod-List#22]
If you press shift on a block of IC2, all the authors (a lot) get listed and the screen is bloated.

**Comment by Lanse505** [comment]
This should be.... Waila Features? doing that.

**Comment by Lanse505** [comment]
@SkySom

**Comment by JorVaCoding** [comment]
It's client side... In wailafeatures config, change ```B:"Activate Mod Author Identification"=true``` to ```B:"Activate Mod Author Identification"=false```
