### ISSUE TITLE
Request some mods to be added

### ISSUE THREAD

**Issue by InfinityRaider** [ModdersCorner/404-Mod-List#23]
3D Maneuver Gear:
http://minecraft.curseforge.com/projects/d-maneuver-gear/files/2317217

NinjaGear:
http://minecraft.curseforge.com/projects/ninjagear/files/2317223

**Comment by JorVaCoding** [comment]
They both look like good mods, I'm concerned about the json models though... The players that lag on the server will lag a lot more of people are running around with fancy json armours...

**Comment by SkySom** [comment]
Those are his mods yo. He wants them tested a bit. They're good to go.

**Comment by InfinityRaider** [comment]
What json models? There are no json models, except for flat 2D item textures.

**Comment by JorVaCoding** [comment]
Well in that case, I say add it.
