### ISSUE TITLE
Reliquary

### ISSUE THREAD

**Issue by Eladkay** [ModdersCorner/404-Mod-List#25]
http://minecraft.curseforge.com/projects/reliquary-v1-3

**Comment by JorVaCoding** [comment]
I wanted to suggest this, but it's a little buggy. It's a good mod and has a lot of useful items though

**Comment by Lanse505** [comment]
I Vote Yes, It's a good solid mod. It has it's bugs but hopefully if we can get the modder on Discord we can help him/her hammer the bugs out.

**Comment by yrsegal** [comment]
so long as nothing breaks the server *too* horribly, sounds like a fun addition
