### ISSUE TITLE
Natural Pledge / Botania

### ISSUE THREAD

**Issue by yrsegal** [ModdersCorner/404-Mod-List#27]
http://minecraft.curseforge.com/projects/natural-pledge

I, however, DO want this one to be put up to a vote despite the fact that NP is mine, specifically because Botania is such a huge content mod.

(I, of course, vote yea.)

**Comment by JorVaCoding** [comment]
I feel like we don't have a lot content mods, we have ic2 and roots... I say yes, It would be fun to have more stuff. However: If people complain with the lag, I say no. As long as others are fine, I'm fine with it.

**Comment by yrsegal** [comment]
Botania isn't that laggy.
