### ISSUE TITLE
More Foods 1.18 and Simple Barrels 1.3

### ISSUE THREAD

**Issue by dazsim** [ModdersCorner/404-Mod-List#31]
These 2 mod updates are being released as alpha's for testing soon and i'm looking for feedback.  

More Food 1.18 : this is the beginning of the release of 1.2 content for people to play with.  Wooden Bucket, new crops, new food types, the mob drops have been overhauled and tweaked to give a more balance and the recipes now make use of kaolinite oregen (white clay) for porcelin.  Many more updates and changes, will include in patch notes

Simple Barrels 1.3 : This is another update for Simple Barrels to give finer control of how many items are added/removed when interacting as well as the introduction of fluid barrels and mechanics that make sense for them.  Full changes will be included in patch notes.

**Comment by JorVaCoding** [comment]
http://minecraft.curseforge.com/projects/more-foods

http://minecraft.curseforge.com/projects/simple-barrels

**Comment by yrsegal** [comment]
these are autoincludes since they're by a member of the discord
