### ISSUE TITLE
Translocators

### ISSUE THREAD

**Issue by JorVaCoding** [ModdersCorner/404-Mod-List#32]
http://minecraft.curseforge.com/projects/translocator

**Comment by srs-bsns** [comment]
My opinion on this is the same as my opinion on EnderStorage. Redundant and useless, unless someone specifically needs to test compatibility.

**Comment by yrsegal** [comment]
but so pretty ;-;

**Comment by JorVaCoding** [comment]
Translocators is an easy (and balanced) way of transported items and fluids, ONE block away... It provides compact movement, with upgrades... Its helpful just in general for playing... We have a lot of mods that we don't need to test compat for but we have because it's nice and helps out someone who's actually playing the game. If people wanted to test compat, they can install in a dev env. If people want to have fun while testing, the server is great... It's just testing compat with other mods, some people actually play on it a lot just to play (Warlord and I) and report bugs along the way.

**Comment by Eladkay** [comment]
Fancy multidirectional fluid/item hoppers, why not?

**Comment by warlordjones** [comment]
I'm neutral here. Shouldn't be adding too much bloat? (Slippery slope there though!)
