### ISSUE TITLE
Ender Storage

### ISSUE THREAD

**Issue by JorVaCoding** [ModdersCorner/404-Mod-List#33]
http://minecraft.curseforge.com/projects/enderstorage

**Comment by srs-bsns** [comment]
I'm voting `no` because we already have EnderIO's Dimensional Transceiver for any kind of cross-dimensional transport. EnderStorage would just be redundant and therefore useless, unless someone needs to specifically test compatibility with it.

**Comment by JorVaCoding** [comment]
To my knowledge, EnderIO's Dimension Transceiver doesn't allow liquids...

**Comment by yrsegal** [comment]
it do

**Comment by warlordjones** [comment]
Nope. Just gonna hijack this to say vanilla enderchests are automatable with my Ender Crate ;)
