### ISSUE TITLE
Server mods on the client

### ISSUE THREAD

**Issue by JorVaCoding** [ModdersCorner/404-Mod-List#35]
There's a few mods that only need to be on the server, but are being ran on the client... Causing people to have to download more files, and run more mods on startup...

- DiscordChat
- ServerInfoViewer
- ServerQueryExtender
- RetroGen?

**Comment by SkySom** [comment]
I removed DiscordChat from the last one (It was disabled before), SIV is a client mod, and Retrogen I don't see the issue. If it doesn't crash, then it's just more work on my end to try and make sure things are removed.

**Comment by JorVaCoding** [comment]
```[20:53:42] [Client thread/INFO]: ServerQueryExtender starting up!
[20:53:42] [Client thread/ERROR]: SQE IS A SERVER ONLY MOD! IT WILL NOT WORK ON CLIENTS!```

**Comment by SkySom** [comment]
I've already spoken with K4 about how he could use the @Mod annotation to only load on the specific side.
