### ISSUE TITLE
Bugs after V3 update

### ISSUE THREAD

**Issue by Tbsc** [ModdersCorner/404-Mod-List#37]
- Food can't be eaten when looking at a block
- Psi data gets reset on relogging/server restart
- The Psi spell programmer can't be opened, someone else should probably test it, maybe it was just me
- Pressure plates don't open doors, only close them

**Comment by yrsegal** [comment]
Angel ring only enables flight serverside

**Comment by yrsegal** [comment]
You suffocate *very* fast

**Comment by JorVaCoding** [comment]
@yrsegal Havent tried angel ring yet, Maybe make sure you have enough grid power?

- Lava damage is also ticked very fast (same as suffocation)
- You can only drop items if the whole stack is dropped (SpongeForge)
- CTRL+Q for dropping whole stacks just voids the itemstack and doesn't drop anything

**Comment by yrsegal** [comment]
I do have enough grid power, jorva, it doesn't use it though to fly (at least it doesn't tell us if it is)

**Comment by JorVaCoding** [comment]
It uses grid power... You need to have a certain amount to be flying, It doesnt use fly not in flight though

**Comment by yrsegal** [comment]
Well I had 100, so...
