### ISSUE TITLE
[UPDATE] p455w0rd's Things v0.0.15a

### ISSUE THREAD

**Issue by p455w0rd** [ModdersCorner/404-Mod-List#5]
http://minecraft.curseforge.com/projects/p455w0rds-things/files/2314099

**Comment by p455w0rd** [comment]
yeah this isn't server-stable atm i guess...I have no time to look into it atm..will get it fixed asap n post owkring version here

**Comment by p455w0rd** [comment]
Bugs fixed :)

**Comment by SkySom** [comment]
Updated
