### ISSUE TITLE
Computer Mods

### ISSUE THREAD

**Issue by JorVaCoding** [ModdersCorner/404-Mod-List#6]
I think we should leave open computers for the people who want to use it, (and to avoid issued on world load of getting rid of it). But I'd like to have [ComputerCraft ](http://http://minecraft.curseforge.com/projects/computercraft)since it's been updated to 1.9.
Most people are used to/familiar with computer craft, and I think it'd make for some better automation with our current mod set.

**Comment by SkySom** [comment]
Gonna wait on CC seems there's still a few 1.10 issues that came up, and Dan is still somewhat focusing on 1.9.4 from my understanding?

**Comment by JorVaCoding** [comment]
Well 1.9.4 basically equals 1.10...

**Comment by Lanse505** [comment]
I think we can test both but I am and always will be a bigger fan of OC since it's better documented, more modular and overall a "better" mod IMO.

**Comment by warlordjones** [comment]
I like CC, can't be bothered to learn OC.

**Comment by SkySom** [comment]
Putting this as eventually. There does seem to be several big issues with 1.10 CC. I'll keep checking on it. But I will hold off on adding it.

**Comment by JorVaCoding** [comment]
@warlordjones I can teach you the basics of OC, i don't know it completely, but I can help you get started to the point you can learn how to use it.
