### ISSUE TITLE
PSIonic Upgrades/PSI

### ISSUE THREAD

**Issue by yrsegal** [ModdersCorner/404-Mod-List#8]
http://minecraft.curseforge.com/projects/psionic-upgrades

It adds some fun stuff to psi

**Comment by SkySom** [comment]
Just a reminder to me it'll also require PSI.

**Comment by Lanse505** [comment]
I vote Yes

**Comment by SkySom** [comment]
Silly me, I put this as Feedback Required. It's a community member, it's an auto yes unless there is a reason not.
